### ISSUE TITLE
 Error at docker-compose up --build

### ISSUE THREAD

**Issue by firdavsDev** [m0kr4n3/fastapi_project_template#1]
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

My example .env file:

POSTGRES_SERVER=postgres
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
FIRST_SUPERUSER=postgresql
FIRST_SUPERUSER_PASSWORD=postgresql
USERS_OPEN_REGISTRATION=False

**Comment by m0kr4n3** [comment]
if you're using the postgres docker container than the POSTGRES_SERVER should be named as the `db` container name, which is `db`, or you can change the postgres container in the docker-compose file from `db` to `postgres`. That's the issue that I spotted in your .env file, but concerning the password authentication, the `.env` file is used by both of db and api containers, so it can't be different.

**Comment by firdavsDev** [comment]
> if you're using the postgres docker container than the POSTGRES_SERVER should be named as the `db` container name, which is `db`, or you can change the postgres container in the docker-compose file from `db` to `postgres`. That's the issue that I spotted in your .env file, but concerning the password authentication, the `.env` file is used by both of db and api containers, so it can't be different.

Ok thanks bro :)
